/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.taskhandler.main;

import java.io.IOException;
import java.net.InetSocketAddress;

import com.taskhandler.controller.handlers.GetTasksHandler;

public class App {
	public String getGreeting() {
		return "Hello World!";
	}

	public static void main(String[] args) throws IOException {

		HttpServer server = HttpServer.create(new InetSocketAddress(8080), 0);
		server.createContext("/tasks", new GetTasksHandler());
		server.start();
	}
}
